[versions]
kotlin = "2.0.0"
kotlin-coroutines = "1.9.0-RC"
kotlin-serialization = "1.7.0-RC"
kotlin-datetime = "0.6.0"
kotlin-nodejs = "0.0.7"
ksp = "2.0.0-1.0.21"
ktor = "2.3.11"
slf4j = "2.1.0-alpha1"
clikt = "4.4.0"
gradleplugin = "8.2.0"
kotlin-atomicfu = "0.24.0"
kotlin-compiletesting = "1.6.0"
dokka = "1.9.10"
googleautoservice = "1.1.1"
autoservice-ksp = "1.1.0"
jnanoid = "2.0.0"
ksrpc = "0.9.0"

[libraries]
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
dokka-gradle = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
autoservice = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "autoservice-ksp" }
autoservice-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "googleautoservice" }
kotlin-compiletesting = { module = "com.github.tschuchortdev:kotlin-compile-testing", version.ref = "kotlin-compiletesting"}
ktor-io = { module = "io.ktor:ktor-io", version.ref = "ktor" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialization"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization"}
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines"}
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime"}
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlin-atomicfu"}
kotlinx-nodejs = { module = "org.jetbrains.kotlinx:kotlinx-nodejs", version.ref = "kotlin-nodejs"}
jnanoid = { module = "com.aventrix.jnanoid:jnanoid", version.ref = "jnanoid" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-server = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-kotlinx-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-jackson-serialization = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktor" }
ktor-websockets-serialization = { module = "io.ktor:ktor-websocket-serialization", version.ref = "ktor" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt"}
ksrpc = { module = "com.monkopedia.ksrpc:ksrpc-core", version.ref = "ksrpc"}
ksrpc-sockets = { module = "com.monkopedia.ksrpc:ksrpc-sockets", version.ref = "ksrpc"}
ksrpc-ktor-client = { module = "com.monkopedia.ksrpc:ksrpc-ktor-client", version.ref = "ksrpc"}
ksrpc-ktor-websocket-client = { module = "com.monkopedia.ksrpc:ksrpc-ktor-websocket-client", version.ref = "ksrpc"}

[bundles]
dokka = ["dokka-base", "dokka-gradle"]

[plugins]
ksrpc = { id = "com.monkopedia.ksrpc.plugin", version.ref = "ksrpc"}
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
hierynomus-license = { id = "com.github.hierynomus.license", version = "0.16.1" }
jlleitschuh-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.0.0" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
gmazzo-buildconfig = { id = "com.github.gmazzo.buildconfig", version = "3.1.0" }
